### PR TITLE
Fix broken image

### PR DESCRIPTION
**Pull request by abhirajthakur**
# Description

This is fix of issue #3 .
Now when you new item without the image URL it adds a default image

Screenshot (281)

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Thanks @abhirajthakur, I'll review the changes right away!

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Make sure all checks pass, only then you can merge the PR.

**Review by vanessa-cooper — APPROVED** [review]
Excellent job @abhirajthakur! You're now able to merge the PR.

**Comment by abhirajthakur** [comment]
# Description
This is fix of issue #3 
Now when you new item without the image URL it adds a default image.

Screenshot (281)

**Pull request merged**
